name: ex08
author: |-
  Catalina Vial Moscote
  1221vial@gmail.com
description: Exercice 8 - Cours SIO-2109- Université Laval - Automne 2014
dependencies:
  dartlero:
    git: git://github.com/dzenanr/dartlero.git
